### ISSUE TITLE
Help me understand

### ISSUE THREAD

**Issue by juliocoliveira** [BurdetteLamar/markdown_helper#51]
Hi, i saw your plugin / gem.
And I like to know how to use it to include other file in the markdown.

I already included it on my github pages.
But your documentation is very confusing, How do I include another file in markdown?

[My file](https://github.com/ZionDevelopers/jframework/blob/gh-pages/_config.yml)

**Comment by BurdetteLamar** [comment]
Thanks, Julio, for your interest.

Your code is php?  To do the file inclusion, you'll need to:

* Install the gem.
* Run the Ruby script that's in bin/include.

If you need help with that, let's take this offline.  I'm at burdettelamar@yahoo.com.

Burdette

**Comment by juliocoliveira** [comment]
I already [did that](https://github.com/ZionDevelopers/jframework/blob/gh-pages/_config.yml), I just need to know how to call the include in markdown.

**Comment by BurdetteLamar** [comment]
Does your template already have the @-prefixed include description(s)?

**Comment by juliocoliveira** [comment]
I did that, but its not working: https://ziondevelopers.github.io/jframework/

**Comment by BurdetteLamar** [comment]
K, in your index.md, I see '@[:verbatim](README.md)'.

The markdown helper's include method is a pre-processor.  It can can read your index.md and write a new.md that has the included file.  Then the new.md should be pushed to your repo.

Have you, in a shell, run bin/include?

**Comment by juliocoliveira** [comment]
I though that your plugin would work by itself, without the need of anything else.

**Comment by juliocoliveira** [comment]
Well thanks anyway.

**Comment by BurdetteLamar** [comment]
Julio, see if this helps:

https://github.com/BurdetteLamar/markdown_helper/blob/master/readme_files/use_cases/reusable_text/use_case.md

**Comment by BurdetteLamar** [comment]
(Should have reopened.)

**Comment by juliocoliveira** [comment]
Thanks but still it should work by itself without need to run an external program, to work with GitHub Pages and with Jekyll

**Comment by abhishekt572** [comment]
I am trying to use the markdown_helper in my md file. I am trying to include a reusable footer in each and every md file in my project. I am using **@[:markdown](./index-footer.md)** annotation in the file where footer needs to be included and I am running the command **/usr/gem/bin/markdown_helper include --pristine /srv/jekyll/user-guide/index.md   /srv/jekyll/user-guide/index-footer.md**  in my container where **/srv/jekyll/user-guide/index.md** is the md file which would include the footer and **/srv/jekyll/user-guide/index-footer.md** is reusable footer. here after running the command the footer file is updated and includes the content of the user-guide file and on using the same with other files the footer file keeps on appending the content init leading to footer file showing all the content of various pages altogether.

Need help on this.

**Comment by BurdetteLamar** [comment]
> Need help on this.

As near as I can tell, you've specified the includable footer as the output.  The first file to cite is the one containing the include directives; the second file to cite is the file to be written, containing everything from the first file, along with included text.

Your includable footer is neither of these, and should not be on the command line, but only in the include directives.

Here's the help:

```
Usage: markdown_helper include [options] template_file_path markdown_file_path

@abhishekt572, ping me again if this does not solve.
        --pristine                   No comments added
        --help                       Display help

  where

    * template_file_path is the path to an existing file.
    * markdown_file_path is the path to a file to be created.

  Typically:

    * Both file types are .md.
    * The template file contains file inclusion descriptions.
```
